<?php
namespace Article;
$title = $this->translate("Articles", __NAMESPACE__);
$this->headTitle($title);
?>
<ul class="nav nav-tabs">
  <li <?php if($tab=="articles"){ echo 'class="active"'; }?>><a href="#articles" data-toggle="tab"><?php echo $this->translate("Articles", __NAMESPACE__);?></a></a></li>
  <li <?php if($tab=="articlesGroups"){ echo 'class="active"'; }?>><a href="#articlesGroups" data-toggle="tab"><?php echo $this->translate("Articles groups", __NAMESPACE__);?></a></li>
</ul>

<!-- --------------------------------------------------------------------------------------------- -->
<div class="tab-content">
<div class="tab-pane <?php if($tab=="articles"){ echo 'active'; }?>" id="articles">
<h2><?php echo $this->escapeHtml($title); ?></h2>
<p>
    <a class="btn btn-small" href="<?php echo $this->url('zfcadmin/articles-administration', array('action'=>'add'));?>">
        <i class="icon-plus"></i>&nbsp;<?php echo $this->translate("Add article", __NAMESPACE__);?>
    </a>
</p>

<table class="table">
<tr>
    <th><?php echo $this->translate("Active", __NAMESPACE__);?></th>
    <th class="span5"><?php echo $this->translate("Title", __NAMESPACE__);?></th>
    <th><?php echo $this->translate("Group", __NAMESPACE__);?></th>
    <th><?php echo $this->translate("Created", __NAMESPACE__);?></th>
    <th><?php echo $this->translate("Display wysiwyg", __NAMESPACE__);?></th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($articles as $article) : ?>
<tr>
    <td><?php if($article->getActive()){?><i class="icon-ok"></i><?php }else{ ?><i class="icon-remove"></i><?php }?>
    </td>
    <td><?php echo $article->getTitle();?></td>
    <td><?php echo $article->getArticlesGroup()->getName();?></td>
    <td><?php echo $article->getCreated()?$article->getCreated()->format('d.m.Y H:i:s'):""; ?></td>
    <td><?php if($article->getDisplayWysiwyg()){?><i class="icon-ok"></i><?php }else{ ?><i class="icon-remove"></i><?php }?>
    <td>
        <a class="btn btn-small btn-warning" href="<?php echo $this->url('zfcadmin/articles-administration',array('action'=>'edit', 'id' => $article->getId()));?>">
            <i class="icon-pencil"></i>&nbsp;<?php echo $this->translate("Edit", __NAMESPACE__);?>
        </a>
        <a class="btn btn-small btn-danger" href="<?php echo $this->url('zfcadmin/articles-administration',array('action'=>'delete', 'id' => $article->getId()));?>">
            <i class="icon-remove"></i>&nbsp;<?php echo $this->translate("Delete", __NAMESPACE__);?>
        </a>
    </td>
</tr>
<?php endforeach; ?>
</table>
</div>
    
<!-- --------------------------------------------------------------------------------------------- -->
<div class="tab-pane <?php if($tab=="articlesGroups"){ echo 'active'; }?>" id="articlesGroups">
<h2><?php echo $this->escapeHtml($this->translate("Articles groups", __NAMESPACE__)); ?></h2>
<p>
    <a class="btn btn-small" href="<?php echo $this->url('zfcadmin/articles-administration', array('action'=>'addGroup'));?>">
        <i class="icon-plus"></i>&nbsp;<?php echo $this->translate("Add articles group", __NAMESPACE__);?>
    </a>
</p>

<table class="table">
<tr>
    <th><?php echo $this->translate("Name", __NAMESPACE__);?></th>
    <th><?php echo $this->translate("Articles count", __NAMESPACE__);?></th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($articlesGroups as $articleGroup) : ?>
<tr>
    <td><?php echo $articleGroup->getName();?></td>
    <td><?php echo count($articleGroup->getArticles());?></td>
    <td>
        <a class="btn btn-small btn-warning" href="<?php echo $this->url('zfcadmin/articles-administration',array('action'=>'editGroup', 'id' => $articleGroup->getId()));?>">
            <i class="icon-pencil"></i>&nbsp;<?php echo $this->translate("Edit", __NAMESPACE__);?>
        </a>
        <a class="btn btn-small btn-danger" href="<?php echo $this->url('zfcadmin/articles-administration',array('action'=>'deleteGroup', 'id' => $articleGroup->getId()));?>">
            <i class="icon-remove"></i>&nbsp;<?php echo $this->translate("Delete", __NAMESPACE__);?>
        </a>
    </td>
</tr>
<?php endforeach; ?>
</table>
</div>
</div>