<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Article\Module'                              => __DIR__ . '/Module.php',
    'Article\Controller\AdministrationController' => __DIR__ . '/src/Article/Controller/AdministrationController.php',
    'Article\Controller\ArticleController'        => __DIR__ . '/src/Article/Controller/ArticleController.php',
    'Article\Form\ArticleInputFilter'             => __DIR__ . '/src/Article/Form/ArticleInputFilter.php',
    'Article\Form\ArticleForm'                    => __DIR__ . '/src/Article/Form/ArticleForm.php',
    'Article\Entity\Article'                      => __DIR__ . '/src/Article/Entity/Article.php',
);