<?php

namespace Application;
?>
<h2><?php echo $this->translate("Administration", __NAMESPACE__); ?></h2>
<div class="row"> 
    <!--
    <div class="span3"> 
        <div class="well" style="padding: 8px 0;"> 
            <ul class="nav nav-list"> 
                <li class="nav-header"> 
                    Admin
                </li> 
                <li class="active"> 
                    <a href="#"><i class="icon-white icon-home"></i> Dashboard</a> 
                </li> 
                <li> 
                    <a href="#"><i class="icon-folder-open"></i> Projects</a> 
                </li> 
                <li> 
                    <a href="#"><i class="icon-check"></i> Tasks</a> 
                </li> 
                <li> 
                    <a href="#"><i class="icon-envelope"></i> Messages</a> 
                </li> 
                <li> 
                    <a href="#"><i class="icon-file"></i> Files</a> 
                </li> 
                <li> 
                    <a href="#"><i class="icon-list-alt"></i> Activity</a> 
                </li> 
                <li class="nav-header"> 
                    Your Account
                </li> 
                <li> 
                    <a href="#"><i class="icon-user"></i> Profile</a> 
                </li> 
                <li> 
                    <a href="#"><i class="icon-cog"></i> Settings</a> 
                </li> 
                <li class="divider"> 
                </li> 
                <li> 
                    <a href="#"><i class="icon-info-sign"></i> Help</a> 
                </li> 
                <li>
                    <ul class="nav nav-list">
                        <li> 
                            <a href="#"><i class="icon-folder-open"></i> Projects</a> 
                        </li> 
                        <li> 
                            <a href="#"><i class="icon-check"></i> Tasks</a> 
                        </li> 
                    </ul>
                </li>
            </ul> 
        </div> 
    </div> 
    -->
    <div class="span12"> 
        <div class="hero-unit"> 
            <h1> 
                <?php echo $this->translate("Wellcome", __NAMESPACE__); ?>
            </h1> 
            <p> 
                <?php echo $this->translate("This is example wellcome page. There is no functionality implemented.", __NAMESPACE__); ?>
            </p> 
            <p> 
                <a href="#" class="btn btn-primary btn-large">Help</a> <a class="btn btn-large">Faq</a> 
            </p> 
        </div> 
        <h2> 
            <?php echo $this->translate("Recent Activity", __NAMESPACE__); ?>
        </h2> 
        <table class="table table-bordered table-striped"> 
            <thead> 
                <tr> 
                    <th> 
                        <?php echo $this->translate("Project", __NAMESPACE__); ?>
                    </th> 
                    <th> 
                        <?php echo $this->translate("Client", __NAMESPACE__); ?>
                    </th> 
                    <th> 
                        <?php echo $this->translate("Type", __NAMESPACE__); ?>
                    </th> 
                    <th> 
                        <?php echo $this->translate("Date", __NAMESPACE__); ?>
                    </th> 
                    <th> 
                        <?php echo $this->translate("View", __NAMESPACE__); ?>
                    </th> 
                </tr> 
            </thead> 
            <tbody> 
                <tr> 
                    <td> 
                        Nike.com Redesign
                    </td> 
                    <td> 
                        Monsters Inc
                    </td> 
                    <td> 
                        New Task
                    </td> 
                    <td> 
                        4 days ago
                    </td> 
                    <td> 
                        <a href="#" class="view-link">View</a> 
                    </td> 
                </tr> 
                <tr> 
                    <td> 
                        Nike.com Redesign
                    </td> 
                    <td> 
                        Monsters Inc
                    </td> 
                    <td> 
                        New Message
                    </td> 
                    <td> 
                        5 days ago
                    </td> 
                    <td> 
                        <a href="#" class="view-link">View</a> 
                    </td> 
                </tr> 
                <tr> 
                    <td> 
                        Nike.com Redesign
                    </td> 
                    <td> 
                        Monsters Inc
                    </td> 
                    <td> 
                        New Project
                    </td> 
                    <td> 
                        5 days ago
                    </td> 
                    <td> 
                        <a href="#" class="view-link">View</a> 
                    </td> 
                </tr> 
                <tr> 
                    <td> 
                        Twitter Server Consulting
                    </td> 
                    <td> 
                        Bad Robot
                    </td> 
                    <td> 
                        New Task
                    </td> 
                    <td> 
                        6 days ago
                    </td> 
                    <td> 
                        <a href="#" class="view-link">View</a> 
                    </td> 
                </tr> 
                <tr> 
                    <td> 
                        Childrens Book Illustration
                    </td> 
                    <td> 
                        Evil Genius
                    </td> 
                    <td> 
                        New Message
                    </td> 
                    <td> 
                        9 days ago
                    </td> 
                    <td> 
                        <a href="#" class="view-link">View</a> 
                    </td> 
                </tr> 
                <tr> 
                    <td> 
                        Twitter Server Consulting
                    </td> 
                    <td> 
                        Bad Robot
                    </td> 
                    <td> 
                        New Task
                    </td> 
                    <td> 
                        16 days ago
                    </td> 
                    <td> 
                        <a href="#" class="view-link">View</a> 
                    </td> 
                </tr> 
                <tr> 
                    <td> 
                        Twitter Server Consulting
                    </td> 
                    <td> 
                        Bad Robot
                    </td> 
                    <td> 
                        New Project
                    </td> 
                    <td> 
                        16 days ago
                    </td> 
                    <td> 
                        <a href="#" class="view-link">View</a> 
                    </td> 
                </tr> 
                <tr> 
                    <td> 
                        Twitter Server Proposal
                    </td> 
                    <td> 
                        Bad Robot
                    </td> 
                    <td> 
                        Completed Project
                    </td> 
                    <td> 
                        20 days ago
                    </td> 
                    <td> 
                        <a href="#" class="view-link">View</a> 
                    </td> 
                </tr> 
            </tbody> 
        </table> 
        <ul class="pager"> 
            <li class="next"> 
                <a href="#">More &rarr;</a> 
            </li> 
        </ul> 
    </div> 
</div> 