<?php

namespace Application;

echo $this->doctype();
?>
<html lang="cs">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate("Application title", __NAMESPACE__))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/docs.css')
                ->prependStylesheet($this->basePath() . '/css/dlu-tw-bootstrap.css')
                ->prependStylesheet($this->basePath() . '/js/jqueryUI/themes/mytheme/jquery-ui.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');
        echo $this->plugin('HeadStyle');
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/init.js')
                ->prependFile($this->basePath() . '/js/application.js')
                ->prependFile($this->basePath() . '/js/ckeditor/ckeditor.js')
                ->prependFile($this->basePath() . '/js/jqueryUI/ui/jquery-ui.custom.js')
                ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery-1.8.0.min.js')
                ->prependFile($this->basePath() . '/js/functions.js');
        ?>
    </head>
    <body data-spy="scroll" data-target=".bs-docs-sidebar">
        <!-- Navbar
        ================================================== -->
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="brand" href="<?php echo $this->url('home'); ?>"><?php echo $this->translate("Application title", __NAMESPACE__); ?></a>

                    <div class="nav-collapse collapse">
                    <?php echo $this->mainMenu('navigation')->setMaxDepth(0)->setUlClass('nav'); ?>
                    </div>
                    <!-- User button -->
                    <div class="btn-group pull-right">
                        <?php if($this->zfcUserIdentity()){ ?>
                        <a class="btn" href="<?php echo $this->url('zfcadmin'); ?>"><i class="icon-user"></i> &nbsp;<?php echo $this->translate("Administration", __NAMESPACE__); ?></a>
                        <?php }else{?>
                        <a class="btn" href="<?php echo $this->url('zfcuser/login'); ?>"><i class="icon-user"></i> &nbsp;<?php echo $this->translate("Sign in", __NAMESPACE__); ?></a>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>

        <!-- Subhead
        ================================================== -->
        <header class="jumbotron subhead" id="overview">
            <div class="container">
                <h1><?php echo $this->translate("Example application", __NAMESPACE__); ?></h1>
                <p class="lead"><?php echo $this->translate("Example application quote", __NAMESPACE__); ?></p>
            </div>
        </header>
        <!-- Container
        ================================================== -->
        <div class="container">
            <div class="row">
                <div class="span2 menu-container">
                    <?php echo $this->mainMenu('navigation')->setUlClass('main-menu span2')->setMaxDepth(null); ?>            
                </div>
            <div class="span10">
                <?php echo $this->flashMessage(); ?>
                <?php echo $this->content; ?>
            </div>
        </div>
        </div> <!-- /container -->
        <footer class="footer">
            <div class="container">
                <p class="pull-right"><a href="#">^ <?php echo $this->translate("Back to top", __NAMESPACE__); ?></a></p>
                <p>&copy; Martin Vágovszký | <?php echo $this->translate("Version", __NAMESPACE__); ?>: <?php echo VERSION; ?> | <a href="http://framework.zend.com">Zend Framework 2</a> &amp; <a href="http://twitter.github.com/bootstrap/">Twitter bootstrap</a> </p>
                <p><?php echo $this->translate("Code licensed under the", __NAMESPACE__); ?> <a href="http://www.apache.org/licenses/LICENSE-2.0" target="_blank">Apache License v2.0</a>. <?php echo $this->translate("Documentation licensed under", __NAMESPACE__); ?> <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</p>
                <p><?php echo $this->translate("Icons from", __NAMESPACE__); ?> <a href="http://glyphicons.com">Glyphicons Free</a>, <?php echo $this->translate("licensed under", __NAMESPACE__); ?> <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</p>
                <ul class="footer-links">
                    <li><a href="http://github.com/vagovszky/y2k"><?php echo $this->translate("Blog source on github", __NAMESPACE__); ?></a></li>
                    <li><a href="http://framework.zend.com"><?php echo $this->translate("Thanks to Zend Framework 2", __NAMESPACE__); ?></a></li>
                    <li><a href="http://twitter.github.com/bootstrap/"><?php echo $this->translate("Styled by twitter bootstrap", __NAMESPACE__); ?></a></li>
                </ul>
            </div>
        </footer>
<?php echo $this->inlineScript(); ?>
    </body>
</html>
