<?php 
namespace Application;
echo $this->doctype(); 
?>
<html lang="en">
  <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate("Application title", __NAMESPACE__))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                  ->prependStylesheet($this->basePath() . '/css/admin.css')
                  ->prependStylesheet($this->basePath() . '/css/style.css')
                  ->prependStylesheet($this->basePath() . '/css/docs.css')
                  ->prependStylesheet($this->basePath() . '/css/dlu-tw-bootstrap.css')
                  ->prependStylesheet($this->basePath() . '/js/jqueryUI/themes/mytheme/jquery-ui.css')
                  ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                  ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');
        echo $this->plugin('HeadStyle');
        echo $this->headScript()
                  ->prependFile($this->basePath() . '/js/init-admin.js')
                  ->prependFile($this->basePath() . '/js/application.js')
                  ->prependFile($this->basePath() . '/js/ckeditor/ckeditor.js')
                  ->prependFile($this->basePath() . '/js/jqueryUI/ui/jquery-ui.custom.js')
                  ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                  ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                  ->prependFile($this->basePath() . '/js/jquery-1.8.0.min.js')
                  ->prependFile($this->basePath() . '/js/functions.js');
        ?>
    </head>

  <body data-spy="scroll" data-target=".bs-docs-sidebar">

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url('zfcadmin') ?>"><?php echo $this->translate("Administration", __NAMESPACE__); ?></a>
          <div class="nav-collapse">
            <p class="navbar-text pull-right">
              <?php echo $this->ZfcUserDisplayName(); ?> | <a href="<?php echo $this->url('home'); ?>"><?php echo $this->translate("Home", __NAMESPACE__); ?></a> | <a href="<?php echo $this->url('zfcuser/logout'); ?>"><?php echo $this->translate("Sign out", __NAMESPACE__); ?></a>
            </p>
            <?php echo $this->navigation('admin_navigation')
                            ->menu()
                            ->setUlClass('nav')
                            ->setMaxDepth(0)
                            ->setRenderInvisible(false)->setTranslatorTextDomain(__NAMESPACE__)?>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container admin-container">
      <?php echo $this->flashMessage(); ?>
      <?php echo $this->content; ?>

    </div> <!-- /container -->
    <footer class="footer">
            <div class="container">
                <p class="pull-right"><a href="#">^ <?php echo $this->translate("Back to top", __NAMESPACE__); ?></a></p>
                <p>&copy; Martin Vágovszký | <?php echo $this->translate("Version", __NAMESPACE__); ?>: <?php echo VERSION; ?> | <a href="http://framework.zend.com">Zend Framework 2</a> &amp; <a href="http://twitter.github.com/bootstrap/">Twitter bootstrap</a> </p>
                <p><?php echo $this->translate("Code licensed under the", __NAMESPACE__); ?> <a href="http://www.apache.org/licenses/LICENSE-2.0" target="_blank">Apache License v2.0</a>. <?php echo $this->translate("Documentation licensed under", __NAMESPACE__); ?> <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</p>
                <p><?php echo $this->translate("Icons from", __NAMESPACE__); ?> <a href="http://glyphicons.com">Glyphicons Free</a>, <?php echo $this->translate("licensed under", __NAMESPACE__); ?> <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>.</p>
                <ul class="footer-links">
                    <li><a href="http://github.com/vagovszky/y2k"><?php echo $this->translate("Blog source on github", __NAMESPACE__); ?></a></li>
                    <li><a href="http://framework.zend.com"><?php echo $this->translate("Thanks to Zend Framework 2", __NAMESPACE__); ?></a></li>
                    <li><a href="http://twitter.github.com/bootstrap/"><?php echo $this->translate("Styled by twitter bootstrap", __NAMESPACE__); ?></a></li>
                </ul>
            </div>
        </footer>
  <?php echo $this->inlineScript() ?>
  </body>
</html>
