<?php
namespace Article;
$title = $this->translate("Articles", __NAMESPACE__);
$this->headTitle($title);
?>
<div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
</div>
<?php
if (count($articles) > 0) {
    foreach ($articles as $article):
        ?>
        <div class="article">
            <h2><?php echo $article->getTitle(); ?></h2>
            <blockquote>
                <p><?php echo $article->getBlockquote(); ?></p>
                <small><?php echo $this->translate("Author", __NAMESPACE__);?>: <?php echo $article->getUser()?$article->getUser()->getDisplayName():'N/A' ?> | <?php echo $article->getCreated()?$article->getCreated()->format('d.m.Y'):"N/A"; ?></small>
            </blockquote>
            <div class="perex">
                <?php echo stripslashes($article->getPerex()); ?>
            </div>
            <p class="pagination-right">
                <a class="btn btn-success" href="<?php echo $this->url('article', array('id' => $article->getId()));?>"><?php echo $this->translate("View article detail", __NAMESPACE__);?> »</a>
            </p>
        </div>        
        <hr />
        <?php
    endforeach;
    echo $this->paginationControl($this->paginator,'Sliding','article/pager.phtml', array('route' => 'articles')); 
}else {
    ?>
    <p class="text-error"><?php echo $this->translate("No articles found", __NAMESPACE__);?></p>
    <?php
}
?>