<?php
namespace Page;
$title = $this->translate("Delete page", __NAMESPACE__);
$this->headTitle($title);
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>

<p><?php echo $this->translate("Are you sure that you want to delete", __NAMESPACE__);?>
    '<?php echo $page->getName(); ?>'?
</p>
<?php
$url = $this->url('zfcadmin/pages-administration', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $page->getId(); ?>" />
    <input type="submit" name="del" value="<?php echo $this->translate("Yes", __NAMESPACE__);?>" />
    <input type="submit" name="del" value="<?php echo $this->translate("No", __NAMESPACE__);?>" />
</div>
</form>