<div class="marketing">
    <h1>Vítejte na Y2k.cz</h1>
    <p class="marketing-byline">Tento web je věnován vývoji v PHP a Zend Frameworku 2.</p>
    <div class="row">
        <div class="span10">
            <div id="myCarousel" class="carousel slide carousel_h">
                <div class="carousel-inner carousel_h">
                    <div class="item active carousel_h">
                        <img src="<?php echo $this->basePath(); ?>/img/wall1.jpg" alt="" class="carousel_h">
                        <div class="carousel-caption">
                            <h4>Jednoduše a efektně</h4>
                            <p>Moderní webové technologie umožňují jednodušše psát efektní aplikace, využijme toho.</p>
                        </div>
                    </div>
                    <div class="item carousel_h">
                        <img src="<?php echo $this->basePath(); ?>/img/wall2.jpg" alt="" class="carousel_h">
                        <div class="carousel-caption">
                            <h4>Rozvíjejme své dovednosti</h4>
                            <p>Nezamrzněme v pravěku a věnujme se rozšiřování svých obzorů.</p>
                        </div>
                    </div>
                    <div class="item carousel_h">
                        <img src="<?php echo $this->basePath(); ?>/img/wall3.jpg" alt="" class="carousel_h">
                        <div class="carousel-caption">
                            <h4>Mějme radost z toho, že se dílo daří</h4>
                            <p>Sami se přesvěčte o tom, že když se Vám začne rýsovat pěkná aplikace pod rukama, je to skvělý pocit.</p>
                        </div>
                    </div>
                </div>
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span4">
            <h2>Forkněte si tento web</h2>
            <p>Na mém <a href="https://github.com/vagovszky/workspace">githubu</a> si můžete stáhnout zdrojové kódy těchto www a dělat si s nimi co Vás napadne. Doporučuji zejména jako lehkou inspiraci pro ty, kteří se chtějí blíže seznámit s tvorbou aplikací v <a href="https://framework.zend.com">Zend Frameworku 2</a></p>
        </div>
        <div class="span4">
            <h2>Inspirujte se</h2>
            <p>Snažil jsem se zdrojové kódy tohoto webu udělat pěkné, přehledné a škálovatelné a to tak abych si usnadnil práci při tvorbě dalších podobných stránek. Pokud jste již alespoň mírně pokročilý programátor/ka, jistě tyto zdrojové kódy pro vás budou užitečnou inspirací</p>
        </div>
        <div class="span4">
            <h2>Zapojte se</h2>
            <p>Pokud by se mezi Vámi našli odvážlivci, kteří by měli zájem se aktivně podílet na vývoji, neváhejte mě kontaktovat, či využít githubu. Budu rád, když se dílko bude rozšiřovat.</p>
        </div>
        

   
    
    </div>
    <div class="row-fluid">
        <hr class="soften">
        <div class="span11">
        <blockquote>
            <p>Jsme rozlišeni přízvukem svých zájmů, svých věr a svých názorů, ale žádná různost nemůže zastřít základní potřebu nás všech, potřebu svobody a vývoje.</p>
            <small><cite title="Vančura">Vančura</cite></small>
        </blockquote>
    </div>
    </div>

</div>