<div class="marketing">
    <h1>歡迎來到 H2o</h1>
    <p class="marketing-byline">本網站致力於開發PHP和Zend Framework 2</p>
    <div class="row">
        <div class="span10">
            <div id="myCarousel" class="carousel slide carousel_h">
                <div class="carousel-inner carousel_h">
                    <div class="item active carousel_h">
                        <img src="<?php echo $this->basePath(); ?>/img/wall1.jpg" alt="" class="carousel_h">
                        <div class="carousel-caption">
                            <h4>輕鬆和有效率</h4>
                            <p>現代網絡技術提供了強大的應用程序更容易編寫，讓我們使用它。</p>
                        </div>
                    </div>
                    <div class="item carousel_h">
                        <img src="<?php echo $this->basePath(); ?>/img/wall2.jpg" alt="" class="carousel_h">
                        <div class="carousel-caption">
                            <h4>培養自己的技能</h4>
                            <p>凍結在史前時代，讓我們來擴大自己的視野。</p>
                        </div>
                    </div>
                    <div class="item carousel_h">
                        <img src="<?php echo $this->basePath(); ?>/img/wall3.jpg" alt="" class="carousel_h">
                        <div class="carousel-caption">
                            <h4>讓我們做的工作有喜悅</h4>
                            <p>事實上，當你開始初具規模下手中的一個很好的應用，這是一個偉大的應用。</p>
                        </div>
                    </div>
                </div>
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span4">
            <h2>H2o 本網</h2>
            <p>在我的 <a href="https://github.com/hale0124/H2o.git">githubu</a> 你可以下載源代碼的網頁，並與他們你的想法。我建議主要是為那些誰想要了解更多關於構建應用程序在光的靈感 <a href="https://framework.zend.com">Zend Framework 2</a></p>
        </div>
        <div class="span4">
            <h2>啟發</h2>
            <p>我試過這個網站的源代碼一個不錯的，清晰的和可擴展性，它促進了我的工作在其他類似網站的創建。如果你有中級以上水平程序員/ KA，當然，這些源代碼將是對您有用的啟示</p>
        </div>
        <div class="span4">
            <h2>加入</h2>
            <p>如果您發現該冒險者，誰願意積極參與的發展，不要猶豫與我聯繫，或使用GitHub。我會很高興的藝術作品將擴大。</p>
        </div>
        

   
    
    </div>
    <div class="row-fluid">
        <hr class="soften">
        <div class="span11">
        <blockquote>
            <p>我們是一個傑出的口音，以他們的利益，他們的信仰和他們的意見，但沒有各種無法掩飾我們所有的人的基本需要，自由和發展的需要。</p>
            <small><cite title="Vančura">Hale</cite></small>
        </blockquote>
    </div>
    </div>

</div>