<?php

namespace Category;
?>
<h2><?php echo $this->translate("Categories - delete", __NAMESPACE__); ?></h2>
<div class="row"> 
    <div class="span3"> 
        <div class="well" style="padding: 8px 0;"> 
            <!-- Navigation -->
            <?php echo $this->navlist($category, $root, $id); ?>
            <!-- /Navigation -->
        </div> 
    </div> 
    <div class="span9">
        <div class="alert alert-info">
                <button class="close" data-dismiss="alert" type="button">×</button>
                <strong><?php echo $this->translate("Info", __NAMESPACE__);?>:</strong>
                <?php echo $this->translate("This choice can delete category", __NAMESPACE__);?>
            </div> 
        <div class="well">
        <p class="text-error"><?php echo $this->translate("Are you sure that you want to delete category", __NAMESPACE__); ?>?</p>
        <?php
        $url = $this->url('zfcadmin/categories-administration', array('action' => 'delete','id' => $id));
        ?>
        <form action="<?php echo $url; ?>" method="post">
            <div>
                <input type="hidden" name="id" value="<?php echo $id; ?>" />
                <input class="btn btn-danger" type="submit" name="del" value="<?php echo $this->translate("Yes", __NAMESPACE__); ?>" />
                <input class="btn" type="submit" name="del" value="<?php echo $this->translate("No", __NAMESPACE__); ?>" />
            </div>
        </form>
        </div>
    </div>
</div>
