<?php
namespace Category;
?>
<h2><?php echo $this->translate("Categories - edit", __NAMESPACE__); ?></h2>
<div class="row"> 
    <div class="span3"> 
        <div class="well" style="padding: 8px 0;"> 
            <!-- Navigation -->
            <?php echo $this->navlist($category, $root, $id); ?>
            <!-- /Navigation -->
        </div> 
    </div> 
    <div class="span9">
           <?php
            $form = $this->form;
            $formType = $this->formType;
            $validData = $this->validData;
            $form->setAttribute('action', $this->url('zfcadmin/categories-administration', array('action' => 'edit','id' => $id)));
            $form->prepare();
            $displayOptions = array();
            if ($form->getMessages()):
                ?>
                <div class="alert alert-error">
                    <button class="close" data-dismiss="alert" type="button">×</button>
                    <strong><?php echo $this->translate("Invalid input", __NAMESPACE__); ?>!</strong>
                <?php echo $this->translate("The form fields are not filled out correctly", __NAMESPACE__); ?>.
                </div>
            <?php elseif ($validData): ?>
                <div class="alert alert-success">
                    <button class="close" data-dismiss="alert" type="button">×</button>
                    <strong><?php echo $this->translate("Form data is valid", __NAMESPACE__); ?>!</strong>
                <?php echo $this->translate("The following data has been received from the form", __NAMESPACE__); ?>.
                </div>
                <?php echo($validData); ?>
            <?php else: ?>
                <div class="alert alert-info">
                    <button class="close" data-dismiss="alert" type="button">×</button>
                    <strong><?php echo $this->translate("Submit the form", __NAMESPACE__); ?>:</strong>
                <?php echo $this->translate("Fill this form and submit", __NAMESPACE__); ?>
                </div>
            <?php
            endif;
            ?>
        <p>
            <a class="btn" href="<?php echo $this->url('zfcadmin/categories-administration',array('action'=>'add')); ?>">
                <i class="icon-plus"></i>
                &nbsp;<?php echo $this->translate("Add category to /", __NAMESPACE__);?>
            </a>
            <a class="btn" href="<?php echo $this->url('zfcadmin/categories-administration',array('action'=>'add', 'id'=>$id)); ?>">
                <i class="icon-plus"></i>
                &nbsp;<?php echo $this->translate("Add subcategory", __NAMESPACE__);?>
            </a>
            <a class="btn btn-danger" href="<?php echo $this->url('zfcadmin/categories-administration',array('action'=>'delete', 'id'=>$id)); ?>">
                <i class="icon-remove"></i>
                &nbsp;<?php echo $this->translate("Delete with subcategories", __NAMESPACE__);?>
            </a>
        </p>
        <hr>
            <?php echo $this->formTwb($form, $formType, $displayOptions); ?>
        </div>
</div>
